#!/bin/zsh
function externalServicesFFS() {
    CUR_DIR=${PWD}
    FFS_DIR="$HOME/Work/ffs/externalServices"

    cd ${FFS_DIR}
    if [ "$#" -ne 1 ]; then
        ./Status-External-Services.sh
    elif [ "$1" = "start" ]; then
        ./Start-External-Services.sh
    elif [ "$1" = "stop" ]; then
        ./Stop-External-Services.sh
    elif [ "$1" = "status" ]; then
        ./Status-External-Services.sh
    else
        echo "Incorrect usage, try: $0 [<start|stop|status>]"
        exit 1
    fi

    cd ${CUR_DIR}
}

externalServicesFFS "$@"
