#!/bin/zsh
function invalid_usage () {
    echo "Incorrect usage, try: $0 <start|stop>"
}

function runFfs () {
    CUR_DIR=${PWD}
    FFS_DIR="$HOME/Work/ffs"
    FFS_SERVER_DIR="${FFS_DIR}/ffs-server/target"

    if [ "$#" -ne 1 ]; then
        invalid_usage
    elif [ "$1" = "start" ]; then
        cd ${FFS_SERVER_DIR}/ffs-server-*-ffs-admin/ffs-admin
        ./bin/start.sh
    elif [ "$1" = "tail" ]; then
        cd ${FFS_SERVER_DIR}/ffs-server-*-ffs-admin/ffs-admin
        ./bin/start.sh
        tail -f ${FFS_DIR}/ffs-server/server/logs/ffs.log
    elif [ "$1" = "stop" ]; then
        cd ${FFS_SERVER_DIR}/ffs-server-*-ffs-admin/ffs-admin
        ./bin/stop.sh
    else
        invalid_usage
    fi

    cd ${CUR_DIR}
}

runFfs "$@"
